-- users
CREATE TABLE users (
  id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  name             VARCHAR2(100) NOT NULL,
  email            VARCHAR2(150) NOT NULL,
  password         VARCHAR2(255) NOT NULL,
  two_factor_auth  CHAR(1) DEFAULT 'N' CHECK (two_factor_auth IN ('Y','N')),
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,

  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

-- users
CREATE TABLE companies (
  id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  name       VARCHAR2(120) NOT NULL,
  cnpj       VARCHAR2(20)  NOT NULL,
  type       VARCHAR2(50),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,

  CONSTRAINT pk_companies PRIMARY KEY (id),
  CONSTRAINT uq_companies_cnpj UNIQUE (cnpj)
);

-- cryptos
CREATE TABLE cryptocurrencies (
  id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  name           VARCHAR2(60) NOT NULL,
  symbol         VARCHAR2(10) NOT NULL,
  previous_price NUMBER(18,8),
  price          NUMBER(18,8) NOT NULL,
  last_updated   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at     TIMESTAMP,

  CONSTRAINT pk_cryptocurrencies PRIMARY KEY (id),
  CONSTRAINT uq_cryptos_symbol UNIQUE (symbol)
);

-- investments
CREATE TABLE investments (
  id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  user_id     NUMBER(19) NOT NULL,
  company_id  NUMBER(19) NOT NULL,
  crypto_id   NUMBER(19) NOT NULL,
  amount      NUMBER(18,8) NOT NULL,
  price       NUMBER(18,8) NOT NULL,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at  TIMESTAMP,

  CONSTRAINT pk_investments PRIMARY KEY (id),
  CONSTRAINT fk_inv_user    FOREIGN KEY (user_id)    REFERENCES users(id),
  CONSTRAINT fk_inv_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_inv_crypto  FOREIGN KEY (crypto_id)  REFERENCES cryptocurrencies(id)
);

-- indexes
CREATE INDEX idx_inv_user    ON investments(user_id);
CREATE INDEX idx_inv_company ON investments(company_id);
CREATE INDEX idx_inv_crypto  ON investments(crypto_id);

ALTER TABLE investments ADD CONSTRAINT chk_inv_amount_pos CHECK (amount > 0);
ALTER TABLE investments ADD CONSTRAINT chk_inv_price_pos  CHECK (price  > 0);
